packages:
  - "packages/*"
  - "apps/*"

patchedDependencies:
  void@0.10.12: patches/void@0.10.12.patch

allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  msw: true
  sharp: true
  workerd: true

minimumReleaseAge: 1440
