packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  msw: true
  sharp: true
  workerd: true

minimumReleaseAge: 1440

patchedDependencies:
  exifr@7.1.3: patches/exifr@7.1.3.patch
