/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as HaulRouteImport } from './routes/haul'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const HaulRoute = HaulRouteImport.update({
  id: '/haul',
  path: '/haul',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/haul': typeof HaulRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/haul': typeof HaulRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/haul': typeof HaulRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/haul' | '/snapshot' | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/haul' | '/snapshot' | '/upload'
  id: '__root__' | '/' | '/haul' | '/snapshot' | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HaulRoute: typeof HaulRoute
  SnapshotRoute: typeof SnapshotRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haul': {
      id: '/haul'
      path: '/haul'
      fullPath: '/haul'
      preLoaderRoute: typeof HaulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HaulRoute: HaulRoute,
  SnapshotRoute: SnapshotRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
