/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HaulIndexRouteImport } from './routes/haul/index'
import { Route as HaulAddRouteImport } from './routes/haul/add'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HaulIndexRoute = HaulIndexRouteImport.update({
  id: '/haul/',
  path: '/haul/',
  getParentRoute: () => rootRouteImport,
} as any)
const HaulAddRoute = HaulAddRouteImport.update({
  id: '/haul/add',
  path: '/haul/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
  '/haul/add': typeof HaulAddRoute
  '/haul/': typeof HaulIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
  '/haul/add': typeof HaulAddRoute
  '/haul': typeof HaulIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
  '/haul/add': typeof HaulAddRoute
  '/haul/': typeof HaulIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/snapshot' | '/upload' | '/haul/add' | '/haul/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/snapshot' | '/upload' | '/haul/add' | '/haul'
  id: '__root__' | '/' | '/snapshot' | '/upload' | '/haul/add' | '/haul/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SnapshotRoute: typeof SnapshotRoute
  UploadRoute: typeof UploadRoute
  HaulAddRoute: typeof HaulAddRoute
  HaulIndexRoute: typeof HaulIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haul/': {
      id: '/haul/'
      path: '/haul'
      fullPath: '/haul/'
      preLoaderRoute: typeof HaulIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haul/add': {
      id: '/haul/add'
      path: '/haul/add'
      fullPath: '/haul/add'
      preLoaderRoute: typeof HaulAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SnapshotRoute: SnapshotRoute,
  UploadRoute: UploadRoute,
  HaulAddRoute: HaulAddRoute,
  HaulIndexRoute: HaulIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
